### PR TITLE
QGIS_quickstart review

### PR DESCRIPTION
**Pull request by Bakaniko**
Updated a few screenshots and some text.
Grass section is deprecated, can't fix it.

800x600/qgis_toolbox.png and 800x600/qgis_enable_provider.png can be removed (1024x768 versions committed)

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @Bakaniko 
We cannot yet remove those images, not all translations have moved to the new version...

**Comment by kalxas** [comment]
New PR including this one: #117

**Comment by Mloweedgar** [comment]
Hi every one. may be am a bit out of the topic but am looking for any one who could help me on how to grass plug-in in QGIS to detect the flood prone areas. I have heard of the r.hazard.flood module which is used to detect flood prone areas. but I cannot find r.hazard.flood module in grass  toolbox in the QGIS. please if there is anyone who can help me on that

**Comment by kalxas** [comment]
@Mloweedgar please use the grass mailing list for support.

**Pull request closed without merging**
