### PR TITLE
pgRouting updates to reflect pgRouting 2.1+ and osm2pgrouting 2.1+, minor PostGIS edits

### PR DESCRIPTION
**Pull request by robe2**
I added a section for osm2pgrouting load and revised the examples to reflect new function signatures for pgRouting 2.1+

### CODE REVIEW

**Comment by camerons** [comment]
Thanks Regina for this update. Initial review comments:
* If you haven't already done so, I suggest having a look at the writing tips in https://raw.githubusercontent.com/OSGeo/OSGeoLive-doc/master/en/quickstart/udig_quickstart.rst (which is our reference quickstart doc).
* This quickstart is all demonstrated through the command line interface. Is there a GUI interface that can be used? We want to also be able to target new users with minimal to no programming experience. If so, then I suggest including screen shots with a simple routing example using the GUI.
* With osgeolive quickstarts, we make the assumption that people are using OSGeo-Live, and we are also trying to keep the quickstart simple and brief. So no need to describe how to install things which are already on osgeo-live, or check versions of applications. 
* Note, there is a typo: "This Quick Start describes install pgrouting..." should be "This Quick Start describes how to install pgrouting..."

**Comment by robe2** [comment]
@camerons I made wording change you suggested, but also changed the word installing to enabling since it really talks about enabling pgRouting in a database, rather than installing pgRouting, which as you noted is already installed.

As to putting in figures, I'd rather not at this time because that takes more bandwidth than I currently have and would make the quick start longer than 5 minutes (as your reference quickstart suggests it should be). 

As to including version numbers and showing people how they know what version they are running, I think this is important for a couple of reasons.

1. It shows the vintage of OSGeoLive which is relevant to determine if the documentation needs updating for future versions. e.g. I can look at the docs and say - hey we are at pgRouting 2.3 and they are talking about pgRouting 2.2 (let me see what needs changing).  Rather than guessing based on what the queries are that are being run.

2. I think it's important people understand this first step, because ultimately they will want to do this on a production system and if some example doesn't work when they go into production, it could be because they are running something older/newer than what OSGeoLive is describing.  Besides it's a fast exercise to confirm you installed things right.

**Comment by kalxas** [comment]
The only point I see in adding screenshots would be to have some sql queries executed and then show the results on QGIS. After all, pgrouting does not have a GUI.

**Comment by robe2** [comment]
Perhaps I could instead just put a note in there, to see pgRouting query, use QGIS DbManager or OpenJump Ad-Hoc query  to render the output of the geometry.

Then I could just point to the QGIS quick start guide and OpenJump quickstart.guide for futher details..

I was thinking it would actually be nice if the QGIS guide had Db Manager example which I think is a pretty useful extension for PostGIS / pgRouting users and OpenJump also had an ad-hoc example connecting to PostGIS or some other database.  The ad-hoc tools are very useful for spatial database users, but I think really belong in the Desktop tools section.  Though I guess that may make the desktops more than a 5 minute exercise.

**Comment by camerons** [comment]
Hi @robe2, thanks for the updates, I hope to review this weekend. Re using qgis. I'm ok with this release of the quickstart not having a GUI, if you don't have the time for it. But if we do create a QGIS example for pgrouting, I think it should go in the pgrouting quickstart rather than the QGIS one. The QGIS quickstart should focus on very simple QGIS use cases, and not cover a fringe topic such as routing. But I think it is of interest for someone looking at routing to see results in QGIS.

**Comment by camerons** [comment]
I've merged the pgrouting overview and quickstart pull request. Thanks @robe2, it looks good.
Suggestions which I think could be applied to this (or future releases):
1. It would be good to get a screen shot of QGIS using pgrouting.

2. At the moment, you are using the osm feature city as an example. This is cool, but I assume we will need to update the quickstart every year when the osm feature city changes? Better would be to choose a static dataset and reduce our long term maintenance requirements.

**Pull request merged**
