### PR TITLE
Compressing images with pngquant

### PR DESCRIPTION
**Pull request by johanvdw**
On Thu, Jun 4, 2015 at 8:33 PM, Johan Van de Wauw
<johan.vandewauw@gmail.com> wrote:
> Hi all,
>
> I've been experimenting with pngquant [1] to reduce the size of our
> png images in the documentation. This implements a lossy compression
> method, but all images I tried came out just fine.
> In total, we could save about 36Mb by using this compression on all
> files. I believe this is significant enough to do the change for most
> files, especially since they are accessed also over the web by people
> reading the quickstart.
>
> I prepared a branch which contains the compressed images at:
> https://github.com/johanvdw/OSGeoLive-doc/tree/compresspng
> I made a single commit per image, so if we merge we can still roll
> back specific images easily.
> In fact, on github, you can watch the images side by side or as a slide over.

During the meeting last night I proposed fixing only those images
where the difference was most significant (>50% reduction in size and
files of at least 32Kb).
The results are here:
https://github.com/johanvdw/OSGeoLive-doc/tree/compresspng
The result can be downloaded as a package from:
https://launchpad.net/~johanvdw/+archive/ubuntu/osgeolive-docs-compressedpng
And it can be previewed at:
http://gisky.be/osgeolive-docs/en/index.html

In total we save some 34 Mb, most of which is preserved when
compressing the files.

Since I did not see any image which is not good I propose to merge this.

Kind Regards,
Johan

### CODE REVIEW

**Comment by johanvdw** [comment]
Can we merge this? Better merge now rather than wait until conflicts arise.

**Comment by kalxas** [comment]
Based on the meeting discussion (2 or 3 weeks ago), the decision was to use the compression during build time. so not to merge this PR.
@camerons @darkblue-b please confirm.

**Comment by camerons** [comment]
I confirm, it would be preferable if we can compress during build time if we can. That way we don't run the risk of loosing image quality (which might be required for a future use of docs - such as providing high quality paper version).
This will require someone to write image compression into the build process.

**Comment by johanvdw** [comment]
Ok, missed that part. I can add this to the debian build process, shouldn't
be hard.

**Pull request closed without merging**
