### PR TITLE
[WIP] Update SOS documentation

### PR DESCRIPTION
**Pull request by EHJ-52n**
### Description

Latest documentation updates for SOS 4.4.0 for OSGeoLive 11.0

### Status

- [x] Quickstarts (en/de)
- [ ] Overview (en/de)

Work in progress -> please do not merge.

### CODE REVIEW

**Comment by kalxas** [comment]
@EHJ-52n there are conflicts, you have been editing against an older master.
Can you please update your fork and try again?

**Comment by EHJ-52n** [comment]
@kalxas Thanks for the hint. Please do not merge, as it is still work in progress.

**Comment by kalxas** [comment]
ok thanks

**Comment by EHJ-52n** [comment]
@kalxas Could you please merge this in the nightlies, if possible.

**Pull request merged**
