### PR TITLE
Latest documentation updates fpr 52nSOS

### PR DESCRIPTION
**Pull request by EHJ-52n**
- fix timestamps in example requests
- add missing section about bundled client helgoland

### CODE REVIEW

**Comment by kalxas** [comment]
We are currently in a freeze week, will review and merge after 10.5 final is released.

**Comment by kalxas** [comment]
@EHJ-52n There are some comments for the quickstart in our latest review. Can you please check https://docs.google.com/spreadsheets/d/1Q5BaEgQtgw4O1bXyeWMlM8XtAOhUgcjZ7Y2O0FZc2H0/edit#gid=2014800150 
We also need to confirm that the quickstart works fine in 10.5

**Comment by EHJ-52n** [comment]
You talking about 11.0, didn't you?

I am planning to work on the documentation the week after next week. This should be within the limits of the 11.0 roadmap.

**Comment by kalxas** [comment]
We need someone from each project to confirm that the quickstart works on a recent release (10.5 is the latest stable). If you prefer, you can test on a 11.0 nightly, given that your project was recently re-enabled after your PRs.

**Pull request merged**
