### PR TITLE
OSGeo Branding Update Logos

### PR DESCRIPTION
**Pull request by jodygarnett**
I provided these more than a week ago in SVG form, converted to PNG now and added as a pull request.

This pull request also:
- updates the graduation status on a few projects (PostGIS, marble, gvSig, GeoServer)
- changes from incubation to community logo use

### CODE REVIEW

**Comment by jodygarnett** [comment]
Please note this pull request *allows edits from maintainers* - @camerons there should be no need to make your own pull request if you have edits you wish to make no this one. 

> Users with write access to OSGeo/OSGeoLive-doc can add new commits to your logos branch

**Comment by kalxas** [comment]
Thank you @jodygarnett 
This looks really nice!

I will open a ticket on trac and link this PR.

**Comment by kalxas** [comment]
https://trac.osgeo.org/osgeo/ticket/1951

**Comment by camerons** [comment]
I might be nostalgic, but I prefer the old OSGeo Logo, and the blue of our adaption to OSGeo-Live. But I think it valuable to be consistent with OSGeo branding, so I'm in favour of accepting proposed changes for this release. (If we have time to be creative and change the logo later, we can).
+1 from me to accept the new logos.

**Comment by kalxas** [comment]
+1 from me too.
The horizontal banner is much better now, thanks @jodygarnett

**Comment by jodygarnett** [comment]
We can try the blue, as a sub brand it may be fun to have three colours to work with, need someone good it colour theory to choose a complementary shade.

**Comment by jj0hns0n** [comment]
+1, but concur we should continue to explore the boundaries of what we can do with this logo/system and still be 'on brand'

**Comment by kalxas** [comment]
I am not sure we need to keep the Blue.
I also know that @darkblue-b is doing some tests with the logo

**Comment by jodygarnett** [comment]
That is perfect @darkblue-b is already authority on shades of blue (bada ping...)

**Comment by jodygarnett** [comment]
Note the "images/logos/OSGeo_compass_with_text_square.png" logo is against the style guide, I only made it because I wanted to have an unchanged size for our template.  If @darkblue-b is experimenting perhaps we could find where that is used and change to the normal logo.

So what do we need to have happen to merge this pull request?

**Comment by kalxas** [comment]
Since there hasn't been any more feedback here, I will bring this to the mailing list for final voting.

**Comment by cvvergara** [comment]
Hi Jodi,
I don't have write access, so I can not change anything so I will comment:
I took the liberty of making a test merge in my fork, and ran these commands

```
grep OSGeo_community -A 5 $(git ls-files) | more
grep OSGeo_project -A 5 $(git ls-files) | more
```

I will focus this comment on the second command about  `OSGeo_project`:
The majority look like this:
```
ca/overview/deegree_overview.rst:.. image:: /images/logos/OSGeo_project.png
ca/overview/deegree_overview.rst-  :scale: 100
ca/overview/deegree_overview.rst-  :alt: Projecte OSGeo
ca/overview/deegree_overview.rst-  :align: right
ca/overview/deegree_overview.rst-  :target: http://www.osgeo.org
ca/overview/deegree_overview.rst-
```
Some have
-  `:alt: OSGeo Project in Incubation`
-  `:target: http://www.osgeo.org/incubator/process/principles.html`
-  some have both like this one:
```
ca/overview/geomoose_overview.rst:.. image:: /images/logos/OSGeo_project.png
ca/overview/geomoose_overview.rst-  :scale: 100 %
ca/overview/geomoose_overview.rst-  :alt: OSGeo Project in Incubation
ca/overview/geomoose_overview.rst-  :align: right
ca/overview/geomoose_overview.rst-  :target: http://www.osgeo.org/incubator/process/principles.html
ca/overview/geomoose_overview.rst-
```
Some I don't understand the `alt`:
```
el/overview/ossim_overview.rst:.. image:: /images/logos/OSGeo_project.png
el/overview/ossim_overview.rst-  :scale: 100 %
el/overview/ossim_overview.rst-  :alt: Λογισμικό ενσωματωμένο στο OSGeo
el/overview/ossim_overview.rst-  :align: right
el/overview/ossim_overview.rst-  :target: http://www.osgeo.org
el/overview/ossim_overview.rst-
---
el/overview/postgis_overview.rst:.. image:: /images/logos/OSGeo_project.png
el/overview/postgis_overview.rst-  :scale: 100 %
el/overview/postgis_overview.rst-  :alt: Λογισμικό του OSGeo
el/overview/postgis_overview.rst-  :align: right
el/overview/postgis_overview.rst-  :target: http://www.osgeo.org/incubator/process/principles.html
el/overview/postgis_overview.rst-
```

but to be in the safe side, it can be written in English, and later a translator can translate

If you tell me what to do, I can fix and make a PR to your fork/logos branch (that will include the latest changes on master) and you can review the changes, and merge when satisfied (that will update this PR).

**Comment by kalxas** [comment]
@cvvergara I will merge now and we can fix issues in a new PR

**Comment by cvvergara** [comment]
@kalxas 
ok

**Comment by jodygarnett** [comment]
Excellent my first contribution in years breaks the build, I feel like a worthwhile human being :)

(more seriously thanks everyone, it will be great to have the new branding, and the update project relationships, in the mix).

**Comment by cvvergara** [comment]
@jodygarnett 
does not break the build

**Comment by kalxas** [comment]
Actually the test server is still at alpha, not sure if it was this PR :)
http://adhoc.osgeo.osuosl.org/livedvd/docs/en/index.html

**Comment by cvvergara** [comment]
History of VERSION.txt
https://github.com/OSGeo/OSGeoLive-doc/commits/master/VERSION.txt

**Comment by kalxas** [comment]
Back in the subversion days, install scripts and docs were all in one repo.
The VERSION file exists in both git repositories now, but the actual release process is based on this one:
https://github.com/OSGeo/OSGeoLive/commits/master/VERSION.txt

**Comment by cvvergara** [comment]
ah, then that file need be "automatically moved" to the docs repo

**Comment by kalxas** [comment]
@cvvergara actually no.
Since we build the docs as a debian package, the docs become "final" many days before we tag OSGeo-Live as final. So the split is intentional and should stay like that.

**Pull request merged**
