### PR TITLE
Update istsos_overview.rst

### PR DESCRIPTION
**Pull request by mantonovic**
Last check and finalizing istsos overview file

### CODE REVIEW

**Comment by kalxas** [comment]
@mantonovic can you please confirm your agreement with the contribution agreement as per:
https://wiki.osgeo.org/wiki/Live_GIS_Disc#Git_migration

**Comment by mantonovic** [comment]
Thanks @kalxas  I've followed the instruction on the wiki. So I've added my name to the contributors adding that I confirm that my contributions to OSGeo-Live will be compatible with the OSGeo-Live license guidelines at the time of contribution.

**Comment by kalxas** [comment]
Thanks @mantonovic 
Can you please add yourself to https://github.com/OSGeo/OSGeoLive-doc/blob/master/contributors.csv

**Comment by kalxas** [comment]
Oops, sorry, I saw an unmerged version of the file :)

**Pull request merged**
