### PR TITLE
Update on Re3gistry 2 documentation for OSGeoLive 16

### PR DESCRIPTION
**Pull request by oruscalleda**
- Change the logo from INSPIRE Re3gistry to Re3gistry software
- Update the screenshot from INSPIRE Re3gistry to Re3gistry software
- Update the version of the software
- Update on main functionalities of the software

### CODE REVIEW

**Comment by cvvergara** [comment]
@oruscalleda 
Please undo the change on projects_info.csv as the version installed on the disk will be 2.0.0

**Comment by cvvergara** [comment]
We will update that file once we know which version gets intalled

**Review by kalxas — APPROVED** [review]

**Comment by oruscalleda** [comment]
Hi @cvvergara I reverted the changes on the projects_info.csv leaving the old 2.0.0 version.

Also, I have [updated the re3gistry install script](https://github.com/OSGeo/OSGeoLive/pull/365) referring to the tag [v2.4.2](https://github.com/ec-jrc/re3gistry/releases/tag/v2.4.2). I understand these changes (in projects_invo.csv) are made by you later in the process, right?

**Comment by cvvergara** [comment]
>  I understand these changes (in projects_invo.csv) are made by you later in the process, right?

Tes, that is correct

**Pull request merged**
