### PR TITLE
initial commit pygeoapi quickstart

### PR DESCRIPTION
**Pull request by pvgenuchten**
my first pr on this repo, hope things are in place

### CODE REVIEW

**Comment by Bakaniko** [comment]
Hi, @pvgenuchten, thanks for contributing to OSGeoLive.

As you can see I added your project to [projects_info.csv](https://raw.githubusercontent.com/pvgenuchten/OSGeoLive-doc/add-pygeoapi-qs/projects_info.csv) (see [related commit](https://github.com/pvgenuchten/OSGeoLive-doc/commit/3ada28f8f96813c637f9dfe2c1aada943cdb5526). Feel free to complete this part.

Here is some preview of the build :

20201119_pygeopai-contents

It is missing the OSGeo logo and the project name on the left.
I think it is because the overview is missing.
Please change the value in projects_info.csv when the overview is ready, in build it as well.

More info on how to file projects_info.csv here: https://trac.osgeo.org/osgeolive/wiki/How%20to%20configure%20a%20project%20documentation

Quickstart page : 

20201119_pygeopai-quickstart1
20201119_pygeopai-quickstart2
20201119_pygeopai-quickstart3

**Comment by Bakaniko** [comment]
It looks like that in the contents section :


20201119_pygeopai-contents

And the overview like this :
20201119_pygeopai-overview

**Comment by Bakaniko** [comment]
There is an error with  the line 34 of the quickstart : `|osgeolive-appmenupath-pygeoapi|` does not exist.

**Comment by cvvergara** [comment]
Done on #646

**Pull request closed without merging**
