### PR TITLE
Mapserver load wms to qgis

### PR DESCRIPTION
**Pull request by astroidex**
Addes a section to demonstrate that you can use MapServer as OGC WMS and easily load WMS to QGIS or f.e.OpenLayers and Mapbender

Please review and give feeback @aboudreault @Schpidi @sdlime @jmckenna

### CODE REVIEW

**Comment by sdlime** [comment]
@astroidex, we should probably update the list of folks on the MapServer side that should be pinged wrt OSGeo Live. I know Alan (@aboudreault) should be removed, not sure about Stephan (@Schpidi). I'd add Seth (@geographika) if possible.

**Comment by sdlime** [comment]
Couple of typos:

Klick button **New** and add a name and your Servive URL and save your settings:

Should be:

Click button **New** and add a name and your Service URL and save your settings:

**Comment by astroidex** [comment]
thanks @sdlime for the feedback.
I also asked @geographika to join. He agreed

**Comment by geographika** [comment]
@astroidex - I'd probably remove f.e. completely from "the service **f.e.** in a Desktop" (or change to e.g.)

**Comment by astroidex** [comment]
> @astroidex - I'd probably remove f.e. completely from "the service **f.e.** in a Desktop" (or change to e.g.)

done. Thanks for the feedback

**Comment by astroidex** [comment]
thanks for the feeback. Changes are reviewed and can get merged to master

**Pull request merged**
