### PR TITLE
Desk11 scrn

### PR DESCRIPTION
**Pull request by darkblue-b**

### CODE REVIEW

**Comment by kalxas** [comment]
This should not have been merged, the icon is missing...

**Comment by cvvergara** [comment]
@kalxas 
Which icon? ....
you can make a new PR with the change that you want in the image file
The image looks more like the final desktop than the image that was previously.

**Comment by kalxas** [comment]
There should be the Install OSGeo-Live 11.0 icon on the desktop.
I will fix, but every image commit makes our git repo larger...

**Comment by cvvergara** [comment]
Interesting, for me this repo is not too big :)

**Comment by kalxas** [comment]
I am trying to avoid it becoming too big in the near future ;)

**Pull request merged**
