### PR TITLE
demo link fixed

### PR DESCRIPTION
**Pull request by zsiki**

### CODE REVIEW

**Comment by Bakaniko** [comment]
Thanks @zsiki for noticing out. I would like the opinion of @geographika on it. Because it seems the instructions is to create a `demo.html` and work in it. There is also an existing `index.html` with a working example.

So I believe we should let the link like it is, but had the full adress of the already working adress.


Nicolas

**Comment by geographika** [comment]
@Bakaniko - yes this is the intention - the user creates a `demo.html` page as part of the quickstart. If it is confusing perhaps it needs an additional comment?

**Comment by zsiki** [comment]
An additional comment may clear the situation. Anyone can read the quickstart docs on the web and then the demo.html link won't work. I suppose instead of the link you can write please open your html file in the browser.

**Comment by cvvergara** [comment]
@zsiki After the changes on #526 I think this is fixed.
Closing.
If you see the problem again, please open another PR

**Pull request closed without merging**
