### PR TITLE
Adding PIL as a build dependency, since it is needed to scale images

### PR DESCRIPTION
**Pull request by kalxas**
Trying to fix:

http://trac.osgeo.org/osgeo/ticket/1530

### CODE REVIEW

**Comment by johanvdw** [comment]
I'm testing this right now.

**Comment by kalxas** [comment]
@johanvdw did it work?

**Comment by johanvdw** [comment]
I have some troubles with testing in a clean chroot (I'm behind a firewall). The changes certainly don't break anything so I'll merge. We can still ilmprove later should it be necessary

**Comment by kalxas** [comment]
ok, thanks.

**Comment by johanvdw** [comment]
Well, I might have been a bit fast. Got it working but it still needs some changes.

**Comment by johanvdw** [comment]
Can you add also python-pil . Then it works fine (tested on sid).

**Comment by kalxas** [comment]
ok, adding now

**Comment by kalxas** [comment]
thanks @johanvdw 
can we trigger a launchpad re-build?

**Comment by johanvdw** [comment]
On its way...
https://code.launchpad.net/~johanvdw/+recipe/osgeolive-doc-daily

**Comment by kalxas** [comment]
Excellent, thanks!

**Pull request merged**
