### PR TITLE
ZOO-Project 1.6.0 documentation update

### PR DESCRIPTION
**Pull request by gfenoy**
As asked for being kept in OSGeoLive the ZOO-Project quickstart and overview has been updated.

### CODE REVIEW

**Comment by kalxas** [comment]
Hi @gfenoy 
Are the new screenshots optimized for size with optipng or something similar?

**Comment by gfenoy** [comment]
Hi @kalxas 
they are not, do you want me to apply the optimg and pngcrush to both the logo and screenshots ?

**Comment by kalxas** [comment]
The images are very large in size and even if we optimize them on top of the commits, they are already in the git history.... I will need to cherry-pick your commits and commit the images separately.

**Comment by gfenoy** [comment]
Thanks a lot for integrating the modifications and sorry for the issue with images. I will try to not make the same mistake again next time.

**Comment by kalxas** [comment]
No worries, I will do the last step with the images.

**Comment by kalxas** [comment]
Merged

**Pull request closed without merging**
