### PR TITLE
WIP Automatic presentation generation

### PR DESCRIPTION
**Pull request by cvvergara**
Before merging some verifications:

## verification 1: Documentation generation
@Bakaniko 
Please verify that you can you build the documentation locally and it includes the automatic generated presentation.

## verification 2: Contents of the presentation
@astroidex @camerons 

Original presentation.
https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/presentation/index.html

Now the contents:
File that has the non project based slides at the beginning of the presentation:
https://github.com/cvvergara/OSGeoLive-doc/blob/presentation/doc/presentation/start_presentation.txt

For the project based slides:
The notes for the presenter are saved on the project's overview file
@Bakaniko added the notes.
You can click on the commits done and compare  with the original presentation notes.

The idea is that from now on, the presentation notes can be updated while doing the review of the overview contents.

presentation note must be the last thing on the overview file and start with:
```
.. presentation-note
```

Pending for future PR's:
Use the "old css" with this new way of constructing the presentation
Refining details (like images too big for the presentation etc)

### CODE REVIEW

**Comment by cvvergara** [comment]
@Bakaniko instead of using "make html" use "make" (without the html)

**Comment by Bakaniko** [comment]
I'll try it tonight, thanks for the job.

If I build the documentation, the presentation will be build at the same time ?

I saw that I just need to do a make, right ?

**Comment by Bakaniko** [comment]
I started from a clean copy of you repo, @cvvergara .

I used this commands:

 2001  sudo -H pip install git+https://github.com/sphinx-doc/sphinx@stable
 2002  sudo -H pip install sphinx-intl
 2003  sudo -H pip install pip install sphinx-intl
 2004  sudo -H pip install sphinxjp.themes.revealjs
 2005  sudo cpanm Text::SimpleTable::AutoWidth
 2006  git rev-parse --abbrev-ref HEAD
 2007  cd build
 2008  ls
 2009  cd ..
 2010  rm -Rf build/
 2011  mkdir build
 2012  cd build
 2013  cmake -DHTML=ON -DES=ON -@OSGeoLiveDoc_DEBUG=ON ..
 2014  make

I had no error (I had trouble previously to install reveal.js_themes).
But I had no translation in spanish. I tought they were provided by the git repo.

Am I missing something ?

**Comment by cvvergara** [comment]
@Bakaniko 
I havent caputred comleted translations of spanish, only the french

**Comment by Bakaniko** [comment]
There is some missing notes in the presentation (main categories notes like browser facing GIS, desktop GIS)

For example this note is nont presentin the new version:

https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/presentation/index.html#L212

**Comment by cvvergara** [comment]
@Bakaniko 
can you test again that the notes are there, the slides at the end are there, and that you can build the documentation without problems
thanks
:)

**Comment by kalxas** [comment]
Is it time to merge this one?

**Comment by Bakaniko** [comment]
@kalxas I'm a little concern about the 2 failed build with the 2 last commit.
It was some changes I had to do them in order to build locally.

In [7351c58](https://github.com/OSGeo/OSGeoLive-doc/pull/353/commits/7361c583b60b54578b5fc33ce9cb230f141b5733), I removed a command which load parameters from a file and hard coded them in conf.py. It should not be an issue since there is nothing else in the loaded file and there is commented parameters (L16 to L20) from before it was loaded from another file.

For [bc59f17](https://github.com/OSGeo/OSGeoLive-doc/pull/353/commits/bc59f17b1d64afaaf738e5b0c0463c92326b009c), I deactivated  an elseif who check sphinx version (should be > 1.0 which is not an issue with modern ubuntu images).

I think it should build anyway. I don't get it. Any opinion @cvvergara ?

I don't see why we get this error:
The command "pip install git+https://github.com/sphinx-doc/sphinx@stable" failed and exited with 1 during .

Best, 


nicolas

**Comment by Bakaniko** [comment]
Finally :) :+1: @cvvergara

**Comment by kalxas** [comment]
We have tested this with @cvvergara at the code sprint, everything works fine
+1

**Pull request merged**
