### PR TITLE
Update osm_quickstart.rst

### PR DESCRIPTION
**Pull request by althio**
OpenStreetMap Quickstart
- updated intro
- added iD
- updated JOSM
- keep Merkaartor
- added QGIS
- updated Osmosis
- updated osm2pgsql

### CODE REVIEW

**Comment by kalxas** [comment]
Hi @althio and thank you for your contribution!

Can you please send an e-mail to the mailing list (or a message here) that you agree with the license?
Please send something like this:
"Hi all, I'd like to contribute XXX to OSGeo-Live. I confirm that my contributions to OSGeo-Live will be compatible with the OSGeo-Live license guidelines at the time of contribution."
as mentioned in: https://wiki.osgeo.org/wiki/Live_GIS_Disc#Git_migration
Can you please add your name in https://github.com/OSGeo/OSGeoLive-doc/blob/master/contributors.csv as part of this PR?

Thanks,
Angelos

**Comment by althio** [comment]
Hi all, I'd like to contribute this text to OSGeo-Live. I confirm that my contributions to OSGeo-Live will be compatible with the OSGeo-Live license guidelines at the time of contribution.

**Comment by althio** [comment]
Hi @kalxas 
I was unsure about Merkaartor.
Is it still included in OSGeo-Live?

**Comment by kalxas** [comment]
Hi @althio 
Actually we dropped Merkaartor from the disk, but it is still available in our ppa.
Do you feel we need to include it?

**Comment by althio** [comment]
In terms of [OpenStreetMap editors usage](http://wiki.openstreetmap.org/wiki/Editor_usage_stats#by_number_of_users_.28distinct_uids.29), Merkaartor is rather negligible compared to JOSM and iD.
I don't know if it has other merits, I do not use it personally.

**Comment by kalxas** [comment]
Thanks, lets keep it out of the Live for now then and focus on iD and JOSM

**Comment by camerons** [comment]
Hi @althio, the structure of the osm_quickstart is not following our OSGeo-Live template guidelines of providing a 5 to 15 minute example of how to use an application. Hence the desire to switch to the LearnOSM material which has now been added.
My suggestion is that we should now be deprecating this osm_quickstart, replaced by ideditor_quickstart and jsom_quickstart.

**Pull request merged**
