### PR TITLE
Overview fixes

### PR DESCRIPTION
**Pull request by cvvergara**
Fixes [trac 2041](https://trac.osgeo.org/osgeolive/ticket/2041)

Worked with @Bakaniko.

### CODE REVIEW

**Comment by cvvergara** [comment]
A demo of how it currently looks is here:
https://cvvergara.github.io/osgeolive/en/index.html

**Comment by camerons** [comment]
I've had a look at https://cvvergara.github.io/osgeolive/en/index.html . Mostly looks ok, but I did find the following problems:
* From en/index.html the links to Presentation pages are broken. (I would be good if we included a link check as part of our build process)
* From en/overview/overview.html I see we now have a TOC which points to the grouping headings. As this overview.html page is effectively a TOC already, I suggest that we shouldn't include another TOC as well. Also, the TOC is a different font size, which I think looks a bit ugly. This is a cosmetic comment rather than being a show stopper.

**Comment by cvvergara** [comment]
@camerons Thanks for commenting :)

This Pull request only fixes [trac 2041](https://trac.osgeo.org/osgeolive/ticket/2041) the issue opened by @Bakaniko 

## presentation
- I haven't worked on the presentation yet. please open an issue on the trac so Its not forgotten.
## TOC
- Yes, the TOC I added it for "convinience while developing because with it you can jump fast to a particular section, (and some times I need to do it with @Bakaniko when we discuss) for example: 
  - look at Navigation and maps on the vicky demo site using this link: https://cvvergara.github.io/osgeolive/en/overview/overview.html. So you can go see the TOC click and jump.
  - look at Navigation and maps on the OSGeoLive site using this link: https://live.osgeo.org/en/overview/overview.html, scroll down (or use Find)
- I will remove it, because the intention is to generate the documentation like it is currently, please open another issue on the trac so its not forgotten.

I will merge once I see on the trac, the issues you detected. so we don't forget ;)

**Comment by camerons** [comment]
Issue about missing presentation docs raised here: https://trac.osgeo.org/osgeolive/ticket/2042

I've also added a comment with reasoning why I think it better to order projects by "importance" rather than alphabetical order. https://trac.osgeo.org/osgeolive/ticket/2041#comment:4

**Comment by cvvergara** [comment]
@camerons 
Thanks for your comment on the issue, I will not merge this PR because of the original purpose is to have the site like the other and this changes ordering of projects.

I will soon make a demo of how develop looks currently

**Pull request closed without merging**
