### PR TITLE
Update 52nSOS documentation to latest version

### PR DESCRIPTION
**Pull request by EHJ-52n**
- Update en/en quickstart and overview
- Update timestamps in ru quickstart
- Remove outdated quickstarts and overviews of the following languages
  - es
  - ca
  - fr
  - pl
  - zh
  - ko

_By the way, I am on vacation until 20.07. starting today._

### CODE REVIEW

**Comment by kalxas** [comment]
Translations (even if outdated) should not be removed during an update.

**Comment by kalxas** [comment]
Merged (without removals)

**Comment by EHJ-52n** [comment]
@kalxas 

First, thanks for merging and your feedback.
What is the proposed workflow for dealing with outdated translation? Is there any tag or value that can be used for this?

**Comment by kalxas** [comment]
Hi @EHJ-52n 
So far we have not removed outdated translations, since we consider translators responsible for keeping up with the english version.
Perhaps we should re-think this process during a weekly meeting.

**Comment by kalxas** [comment]
There used to be a status web page but the doc build server is stuck (I think)

**Pull request closed without merging**
