### PR TITLE
Add rules to compress some listed images during package build

### PR DESCRIPTION
**Pull request by johanvdw**
This is a rework of the original proposal of updating some images using pngquant.
Images are now compressed while building the debian package.
The list of images that is compressed is in tocompress.txt . This are images whose size will at least be halved with pngquant and which are larger than 32kb. The new and original filesize are also in the file.
The list is generated with the script debian/listimagestocompress.sh . This script is not run automatically, but should be run manually. This way it is possible to exclude files if their result is not good. By not running on all images every build we save a lot of build-time.

We save a total of 50 Mb with this operation (I think this will be more or less the same after compression).

### CODE REVIEW

**Comment by kalxas** [comment]
I like this approach.
+1

**Comment by camerons** [comment]
I'm concerned about introducing a list of images we need to maintain long term, which will be a time sink during builds. I'd prefer that the list be automatically created using some sort of algorithm.

**Comment by kalxas** [comment]
is shrinking all images acceptable for you @camerons ?

**Comment by camerons** [comment]
I'm ok with shrinking all images for the ISO, so long as they look ok. (They don't have to be perfect, just "
"good enough".)

**Comment by johanvdw** [comment]
@camerons : I have included a script that can update the list of images to compress: debian/listimagestocompress.sh

I just don't want to run it on every build as this will take a lot of time. Not running every time also allows us to exclude files manually.

**Comment by kalxas** [comment]
I agree with this plan, lets merge...

**Comment by kalxas** [comment]
@camerons @johanvdw any more comments before I merge? :)

**Comment by camerons** [comment]
@johanvdw @kalxas, I'm in favour of including this functionality, but have a few questions/suggested alternative approaches:
* Why do we now have a debian/ directory? I'm inclined to think that this functionality should be in the bin/ directory with other scripts.
* Should we be compressing images on our web pages at http://live.osgeo.org as well on our ISO? I'd suspect that we have enough space on our website, and need not compress images.
* Compressing the docs should be able to be called from the master Makefile. Probably the existing "make html" continuing to create uncompressed images (for the website), and "make html_compressed" making docs with compressed images, and possibly have a "make compressed_images" which just compresses the images.
* At the moment we are white listing images to compress. I think it probably better to black list images which should not be compressed. This will reduce long term maintenance. As people create new images they will automatically be compressed, unless we see otherwise.

**Comment by kalxas** [comment]
@camerons:

> Why do we now have a debian/ directory? I'm inclined to think that this functionality should be in the bin/ directory with other scripts.

This functionality is only included in the debian folder to keep the docs on web site at full resolution. This PR only affects the docs we install on the disk (trying to save some space)

> Should we be compressing images on our web pages at http://live.osgeo.org as well on our ISO? I'd suspect that we have enough space on our website, and need not compress images.

Correct, the web site version should be uncompressed.

> Compressing the docs should be able to be called from the master Makefile. Probably the existing "make html" continuing to create uncompressed images (for the website), and "make html_compressed" making docs with compressed images, and possibly have a "make compressed_images" which just compresses the images.

Are you willing to apply this change?

> At the moment we are white listing images to compress. I think it probably better to black list images which should not be compressed. This will reduce long term maintenance. As people create new images they will automatically be compressed, unless we see otherwise.

Since the procedure to include images to white list is automated based on size, this will make no difference at all, unless we interfere manually.

**Comment by johanvdw** [comment]
The major disadvantage I see when blacklisting is that build time might be longer. I will try to measure the difference and add it to the discussion.

I think having a make html_compressed makes sense. That way the result can be checked without having to build a debian package. 

As a side note, we should check pull requests containing new images and see if they can be compressed eg https://tinypng.com/ . So we make sure that at least all new images are compact. 

As a second side note, we could look for other images to compress outside the docs dir. I will run my detection script also on the whole disk. I have found some large images eg in geoserver documentation.

**Comment by cvvergara** [comment]
About images of the documentation:

Documentation include "discontinued" packages documentation.

Example:
52nWSS is discontinued
[overview](http://adhoc.osgeo.osuosl.org/livedvd/docs/en/overview/52nWSS_overview.html)
[quickstart](http://adhoc.osgeo.osuosl.org/livedvd/docs/en/quickstart/52nWSS_quickstart.html)
The quick start, is Live based (that is all the instructions are based on a OSGeo live setup)
And its full of images!!!.
The project is "discontinued" are the images are not really useful anymore.

In general, I think that the quick starts of "discontinued" projects are not useful

If the quick start is removed, and also the images that it references to, a lot of space will be "saved". (and/or less images to compress)

I am not suggesting removing the overview it is used on the
"Other software of interest (not available Live)" section
but from the overview remove the quick start link.

**Comment by johanvdw** [comment]
Some information on this last pull request:
I removed the code to compress from the debian dir.
I added the code to the Makefile and a script to list images which can benefit from compression in the bin dir.
The logic to create compressed images is not enabled for the package build and the normal html build. Only when you run `make compressimages` it will build html and compress the image listed in imagestocompress.txt
This file can be generated with `make listimagestocompress` and can manually be updated (eg compress only a selection of files).

**Comment by kalxas** [comment]
This is a great option.
+1

**Pull request merged**
