### PR TITLE
Using sphinx revealjs

### PR DESCRIPTION
**Pull request by cvvergara**
This PR has:
- New `.editorconfig` file that sets the tabs to 2 spaces
- deply action
  - Updates automatically the `locale`
  - will work only when the organization is `OSGeo` therefore forks will not even try to deploy
    - NOTE: testing this will be done with this PR
  - TODO on a future PR to update automatically transifex (still need to manually do a tx push)
- Using sphinx 4.0.0+
- For the presentation:
  - `sphinxjp.themes.revealjs` seems not to be mantained so using `sphinx.revealjs`
  - Adjusted presentation to work with `sphinx.revealjs`
  - Finnaly could make the locale for the presentation to not be empty (it can be transtated on transifex)
- the deploy action
- cmake_minimum_required VERSION 3.2

### CODE REVIEW

**Comment by cvvergara** [comment]
The link: `../../gmt/examples` here is relative to the documentation, but I can not find here any examples directory
```
Look at some of the examples found in: `/usr/share/doc/gmt/examples <../../gmt/examples/>`_
```

**Comment by cvvergara** [comment]
> On second thought, there is no Sphinx 4.0 by default in focal, so this PR is a blocker.
> 
> https://packages.ubuntu.com/focal/sphinx-common

Can it be installed using pip?
```
pip install -r requirements.txt
```

https://github.com/cvvergara/OSGeoLive-doc/blob/using-sphinx-revealjs/requirements.txt

**Comment by cvvergara** [comment]
Maybe we will use on v15?

<h3 id="Future">Future</h3>
<span class="anchor" id="line-88"></span><p class="line867"><span class="anchor" id="line-89"></span></p><p class="line867"><span class="anchor" id="line-90"></span></p><div><p class="line891"></p><p class="line891"></p>

Version | Code name | Docs | Release | End of Life
-- | -- | -- | -- | --
Ubuntu 22.04 | Jammy Jellyfish | Release Notes | April 21, 2022 | April 2027


https://wiki.ubuntu.com/Releases

**Comment by kalxas** [comment]
Pip is not available when building a deb file, we would need to backport sphinx to 20.04

> > On second thought, there is no Sphinx 4.0 by default in focal, so this PR is a blocker.
> > https://packages.ubuntu.com/focal/sphinx-common
> 
> Can it be installed using pip?
> 
> ```
> pip install -r requirements.txt
> ```
> 
> https://github.com/cvvergara/OSGeoLive-doc/blob/using-sphinx-revealjs/requirements.txt

**Comment by kalxas** [comment]
Yes, lets wait for 22.04

> Maybe we will use on v15?
> ### Future
> 
> Version 	Code name 	Docs 	Release 	End of Life
> Ubuntu 22.04 	Jammy Jellyfish 	Release Notes 	April 21, 2022 	April 2027
> 
> https://wiki.ubuntu.com/Releases

**Review by kalxas — APPROVED** [review]

**Pull request merged**
