### PR TITLE
Add code to build github pages from master branch

### PR DESCRIPTION
**Pull request by johanvdw**
This is an example how to create github pages easily using Travis. 
An example output can be seen here: http://johanvdw.github.io/OSGeoLive-doc/en/index.html
Note prior to merging we would need to add a token to travis and switch the branch to master instead of makepages.

### CODE REVIEW

**Comment by kalxas** [comment]
Thank you @johanvdw !
@cvvergara @Bakaniko can you please review?

**Comment by Bakaniko** [comment]
Thanks @johanvdw 

Just one remark, on the branches, I think we should provided a master build for current doc (12.0, 13.0) that we update yearly and one on the dev branch updated at each PR.

Is it possible ?

Thanks for taking it !

**Comment by johanvdw** [comment]
With github pages it is not possible to provide builds for different branches. I believe this is possible though with https://readthedocs.org/ .

On the other hand: the current stable documentation is already published on live.osgeo.org.

**Comment by cvvergara** [comment]
I like the idea to have on github pages the documentation that is under development
and once the version is released then it can go to live.osgeo.org.

**Comment by johanvdw** [comment]
What needs to be done to merge:
* create a user which has access only to this repo
* create a token for that user
* adjust the branch

I'll do this.

**Comment by johanvdw** [comment]
FYI, I have created the: OSGeolive-publishdocs user which will publish the docs.

**Comment by kalxas** [comment]
Thank you @johanvdw 
Docs now available at https://osgeo.github.io/OSGeoLive-doc/en/index.html

**Pull request merged**
