### PR TITLE
[can be merged] Add left logo

### PR DESCRIPTION
**Pull request by cvvergara**
This adds the OSGeo start LOGO before the project name

Full Demo can be seen here:
https://cvvergara.github.io/osgeolive/add-logo-left/en/overview/overview.html

Personally I like this one more. has more ordering on the position of the logo.

PR #283 and this one are incompatible, Merge one and close the other

### CODE REVIEW

**Comment by darkblue-b** [comment]
the logo icon is visually important -- it is very significant if a project is 'Community', 'Official' or none.  Therefore the icon should be a "primary" indicator, not an "additional" indicator..  One way to accomplish this is to make the order   

* [X]  Project Name -- desc
* [Y] Project Name -- desc
* [N] Project Name -- desc

where X -> OSGeo, Y -> Community and N -> an empty icon with the same bounds.
In typesetting and document design, this is considered a 'hack' because printing may not be well aligned. However, it is some work to make real tables instead of lists.. 

I like this idea.

**Comment by cvvergara** [comment]
Just noticed I missed some projects,
I am fixing things

**Comment by cvvergara** [comment]
Added missing logos and aligned the other projects
and looks better.

**Comment by camerons** [comment]
I like the addition of the logo for OSGeo projects. I prefer the logo on the left to the logo in the middle.

**Comment by kalxas** [comment]
+1 for this, it looks much better that #283

**Comment by kalxas** [comment]
MapGuide is also a graduated project.

**Pull request merged**
