### PR TITLE
Update presentation see ticket in trac1959

### PR DESCRIPTION
**Pull request by astroidex**
* see trac ticket https://trac.osgeo.org/osgeo/ticket/1959#ticket
* all 3 presentation files changed

* removed retired projects
* checked image links

**ToDo - open questions**
* how many projects still > 50 ?
* how many projects updated for 11.0? 
* check new in 11.0: long list - menu - does not fit on 2 pages. en/presentation/index.html#/1/4
* suggestion: on slide for OSGEo - delete GNU en/presentation/index.html#/2
* add favicon
* make new screenshot metrics - new OSGeo logo en/presentation/index.html#/1/2
* make new image for slide Production pipeline new OSGeo logo en/presentation/index.html#/1/3
* credits - Thanks to new extended PSC

### CODE REVIEW

**Comment by darkblue-b** [comment]
astroidex -- do you want to make additional changes here?  or is this ready to merge now...

**Comment by astroidex** [comment]
it is ready to merge. Some questions are still open - see above. I would like to discuss them in todays irc meeting

**Comment by camerons** [comment]
@astroidex I've created a first pass review here https://github.com/camerons/OSGeoLive-doc/tree/presentation

**Comment by kalxas** [comment]
@camerons please open a new pull request against master now that this is merged.

**Pull request merged**
