### PR TITLE
actinia: overview and quickstart added

### PR DESCRIPTION
**Pull request by neteler**
- actinia documentation added
- actinia logo added
- metrics added

### CODE REVIEW

**Comment by Bakaniko** [comment]
@neteler 

Sounds good. Can you add your project into [projects_info.csv](https://github.com/OSGeo/OSGeoLive-doc/blob/master/projects_info.csv) so it can be taken in account by the automated build ?

Thanks

**Comment by astroidex** [comment]
@neteler - we approved Actinia  for OSGeoLive in yesterday IRC meeting. 

Please edit https://github.com/OSGeo/OSGeoLive-doc/blob/master/projects_info.csv to show Actinia at the contents overview and metrics page.

**Comment by astroidex** [comment]
looks like @neteler is not available. 
This is why I added the information to the projects_info.csv

@Bakaniko could you please check and merge if ready?

**Comment by cvvergara** [comment]
@neteler 
There were a couple of errors when building the documentation:
There are 2 missing files
I used the logo to substitute them on this PR #470 
- One is a screen shot
the other one is the image ed8775a4bc46415d5c131804ac649936748ad7a7.png 
that you use on the quickstart

```
.. figure:: /images/projects/actinia/ed8775a4bc46415d5c131804ac649936748ad7a7.png
   :alt: ESA Globcover map shown by actinia

   ESA Globcover map shown by actinia
```

Can you please make a PR that changes the files:
* https://github.com/OSGeo/OSGeoLive-doc/blob/master/doc/images/projects/actinia/actinia_screenshot.png

* https://github.com/OSGeo/OSGeoLive-doc/blob/master/doc/images/projects/actinia/ed8775a4bc46415d5c131804ac649936748ad7a7.png

**Comment by neteler** [comment]
I'm traveling, no computer available till end of next week. But the screenshot in question is this one:

https://github.com/mundialis/actinia_core/blob/master/scripts/esa_globcover_rendered_by_ace.png

**Pull request merged**
