### PR TITLE
Add my contribution

### PR DESCRIPTION
**Pull request by Robinlovelace**
I contributed a few visualisation package updates and would like to contribute more in the future, particularly to R documentation. My contributions are compatible with the licence and in the spirit of OSGeo.

### CODE REVIEW

**Comment by camerons** [comment]
Hi Robin, great to have you working with us. Could you please send this statement of compliance with the Open Licenses to Live-demo@lists.osgeo.org (which is our public record of such statements).
Thanks, Cameron Shorter.

**Comment by Robinlovelace** [comment]
Job done - thanks for heads up on that.

**Comment by kalxas** [comment]
@camerons I have not seen the e-mail from @Robinlovelace on the mailing list. 
I am guessing Robin has not subscribed so his e-mail is waiting for approval from the mailing list administrator?

**Comment by camerons** [comment]
Hi @Robinlovelace, we haven't seen your email to Live-demo@lists.osgeo.org. This might be because you did not subscribe to the list before sending it. Could you please subscribe, then resend.http://lists.osgeo.org/mailman/listinfo/live-demo

**Comment by Robinlovelace** [comment]
Hi people it's now been resent - sorry I forgot to register. Let me know if I need o do anything else. Thanks!

**Comment by kalxas** [comment]
Thanks @Robinlovelace

**Pull request merged**
