### PR TITLE
Updating version of pgRouting to 2.4.1

### PR DESCRIPTION
**Pull request by cvvergara**

### CODE REVIEW

**Comment by kalxas** [comment]
Hi @cvvergara 

Since I do not see your name in the contributors list (https://github.com/OSGeo/OSGeoLive-doc/blob/master/contributors.csv) could you please send the following e-mail to the live-demo mailing list as per https://wiki.osgeo.org/wiki/Live_GIS_Disc#Git_migration ?

"Hi all, I'd like to contribute XXX to OSGeo-Live. I confirm that my contributions to OSGeo-Live will be compatible with the OSGeo-Live license guidelines at the time of contribution."

Thanks!

**Comment by cvvergara** [comment]
Do I have to send a mail each time I make a pull request?

**Comment by kalxas** [comment]
Sorry, I just did not find your name in the contributors.csv.
I will add you myself.

**Comment by kalxas** [comment]
You do not need to send an e-mail for each pull request.

**Comment by kalxas** [comment]
Manually merged.

**Pull request closed without merging**
