### PR TITLE
Some news in R overview

### PR DESCRIPTION
**Pull request by ElCep**
For my first pull request I have modified the R overview ... I have added some information, update logo and made a Rstudio Screenshot.

### CODE REVIEW

**Comment by johanvdw** [comment]
If we show a screenshot of RStudio, we should probably also include RStudio in OSGeo live. I personally think we should anyway, but it is quite large.

**Comment by Bakaniko** [comment]
Yes it is big. I'm not sure about the licence of it too.

But we can work on that. :)

**Comment by johanvdw** [comment]
The license of RStudio should not be an issue, it is AGPL, like eg geomajas.

**Comment by kalxas** [comment]
what is the minimal disk space needed for RStudio?

**Comment by kalxas** [comment]
I found a 88mb deb package.
Lets discuss on the next meeting about adding it to the build.

**Comment by darkblue-b** [comment]
note that this PR does not include RStudio, only a screen shot..

**Pull request merged**
