### PR TITLE
update rasdaman version and fix broken links

### PR DESCRIPTION
**Pull request by misev**

### CODE REVIEW

**Comment by cvvergara** [comment]
@misev  
is rasdaman no longer .org?

**Comment by misev** [comment]
It is yes, see http://rasdaman.org

**Comment by cvvergara** [comment]
why then here has a   `.com`?:
```
forward to the `OGC standards showcase site <http://standards.rasdaman.com>`_ .
```

**Comment by misev** [comment]
I think the .org for _that_ particular page has never worked. I could put earthlook.org but it just redirects to http://standards.rasdaman.com anyway.

**Comment by pebau** [comment]
hm, what exactly is bad about a .com?

**Comment by cvvergara** [comment]
Just want to make sure, because rasdaman in an org

**Comment by kalxas** [comment]
nothing wrong with a .com

**Pull request merged**
