### PR TITLE
Otb doc update

### PR DESCRIPTION
**Pull request by gpo-geo**
Update on documentation of OSGeoLive for Orfeo ToolBox
- quickstart and overview updated (english)
- screenshots updated

### CODE REVIEW

**Comment by gpo-geo** [comment]
Hi all, I'd like to contribute  to OSGeo-Live. I confirm that my contributions to OSGeo-Live will be compatible with the OSGeo-Live license guidelines at the time of contribution

**Comment by kalxas** [comment]
Thank you.

**Comment by johanvdw** [comment]
Thanks for your contribution! I see two new contributors? I guess both should mail to the list? https://wiki.osgeo.org/wiki/Live_GIS_Disc

**Comment by kalxas** [comment]
We are sitting next to each other here in Paris ;)

**Comment by kalxas** [comment]
Both contributor agreements are on mailing list now.
Thanks all.

**Pull request merged**
