### PR TITLE
Add notes within presentation

### PR DESCRIPTION
**Pull request by bufferclip**
The presentation shows mostly pictures of the projects. It would be good to show also the text in order to explain the projects.

### CODE REVIEW

**Comment by camerons** [comment]
I notice that "showNotes" changes the HTML from presentation format to presenting all slides with notes in 1 HTML page. I can see how 1 page could be useful, but it was not the primary intent of the OSGeo-Live presentation.
The primary intent was to be used as a slideshow, and that should be the default view.
But, if someone can work out a way to trigger the "showNotes" mode from a button or link on the front page of the slideshow, then we could do that.

**Comment by camerons** [comment]
I notice also that in the "showNotes" mode, the mix of image alignments doesn't work very well. Notes should be underneath images, where as when image alignment is being used, the text is going next to the images.

**Comment by bufferclip** [comment]
For me it stays a presentation with many pages.
It is true that the text sometimes covers the content, but mostly it works.

**Comment by kalxas** [comment]
I agree with Cameron, I would prefer the presentation to remain a slideshow as a default. 
I can also see the point in adding an one-line caption on each slide.

**Pull request closed without merging**
