### PR TITLE
Update gvsig_quickstart.rst

### PR DESCRIPTION
**Pull request by mcarrera77**
I've updated the gvSIG Quickstart guide. It can be published. 
Thank you.

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @mcarrera77 
We will merge after the new version of gvsig is added to the installer:
https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_gvsig.sh#L85

**Comment by kalxas** [comment]
We also have logged in our internal testing this comment:
"The quickstart is quite long, which makes it hard to maintain. If someone reworks this quickstart, it should be made shorter."
Thoughts?

**Comment by mcarrera77** [comment]
Ok, next reviewing we would do it shorter.

**Comment by kalxas** [comment]
Thanks!

**Comment by kalxas** [comment]
Thanks for the review @activityworkshop

**Comment by kalxas** [comment]
@mcarrera77 should we switch back references to 2.2 in this pull request and merge?

**Comment by kalxas** [comment]
Also there is a conflict now, can you please fix this by merging changes that happened in master?

**Comment by mcarrera77** [comment]
Hello, where can I download one of the images to replace? It's the image called "gvsig_qs_032_.png". 
Thank you very much.

**Comment by cvvergara** [comment]
@mcarrera77 
the images are in:
https://github.com/OSGeo/OSGeoLive-doc/tree/master/images/screenshots/1024x768

**Comment by mcarrera77** [comment]
Vicky, could you give me permissions to upload files? Thank you very much.

**Comment by cvvergara** [comment]
@mcarrera77 
I don't have permissions in the main repository. I am a normal person like you,
but, I can give you permissions on my fork.
Let me prepare a branch for you to work in my fork, that includes the changes you made in this PR (without the conflicts).
I'll send a message when the branch is ready

**Comment by cvvergara** [comment]
@mcarrera77 
I guess you are receiving an invitation for collaboration in my fork. please check your mail
The branch I prepared for you is:
https://github.com/cvvergara/OSGeoLive-doc/tree/work/mcarrera
has no conflicts and has @activityworkshop suggested changes

**Comment by kalxas** [comment]
Why not just fork and issue a Pull Request against the main repo?

**Comment by kalxas** [comment]
I suppose we keep this un-merged until we get a new version of gvsig.

**Pull request merged**
