### PR TITLE
Add link to backend in t-rex quickstart

### PR DESCRIPTION
**Pull request by pka**
Add more information as requested by the review.

@astroidex: Was this point you were missing?

### CODE REVIEW

**Comment by astroidex** [comment]
please also add link to metrics to https://github.com/OSGeo/OSGeoLive-doc/edit/master/doc/metrics.rst

https://www.openhub.net/p/t-rex-tileserver/widgets/project_factoids_stats?format=js

> Add more information as requested by the review.
> 
> @astroidex: Was this point you were missing?

I ran the example with the ne.toml. But when I tried to open Geospatial-> Web-Services-T-rex -> nothing happended (no pbrowser/no terminal is opened. When I open the browser manually with the address http://127.0.0.1:6767/ the osm example is dispalyed again

t_rex serve
thread 'main' panicked at 'Can not start server on given IP/Port: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

QUestion:
* how can I see the result of the exercise?
* provide the link to show the ne tiles in the viewer

**Comment by kalxas** [comment]
Shall we merge this one and issue a new PR with the new fixes asked by @astroidex ?

**Comment by pka** [comment]
Holiday wheather looks too good for more changes this week. Will do another pull request with more improvements. I would also like to update t-rex to the latest version. How can I do that, @kalxas?

**Comment by kalxas** [comment]
@pka via a pull request on the code repo:
https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_trex.sh

**Comment by astroidex** [comment]
@pka I will merge it now. but please check the quickstart again

**Pull request merged**
