### PR TITLE
Fix virtualbox quickstart

### PR DESCRIPTION
**Pull request by Bakaniko**
Changes from Woodbri and some by me

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @Bakaniko 
Are those png files optimized for size?

**Comment by Bakaniko** [comment]
I think so, they are the same size than the previous one. Even smaller for
some.

Le 15 juin 2017 23:07, "Angelos Tzotsos" <notifications@github.com> a
écrit :

**Comment by Bakaniko** [comment]
Thanks @kalxas,

It will be on today nightly ?



2017-06-16 15:10 GMT+02:00 Angelos Tzotsos <notifications@github.com>:

**Comment by kalxas** [comment]
check
http://adhoc.osgeo.osuosl.org/livedvd/docs/en/index.html

**Comment by Bakaniko** [comment]
Seems ok to me.

Cheers,

Nicolas

2017-06-17 12:13 GMT+02:00 Angelos Tzotsos <notifications@github.com>:

**Pull request merged**
