### PR TITLE
de - changed cartaro doc ref #1912 and standard ref

### PR DESCRIPTION
**Pull request by astroidex**
* see ticket https://trac.osgeo.org/osgeo/ticket/1912

### CODE REVIEW

**Comment by astroidex** [comment]
added ref to new menu structure to the pull request

**Comment by kalxas** [comment]
Travis fails to build.
Can you please review?

**Comment by cvvergara** [comment]
@kalxas 
for some reason the build was canceled
you should restart it

**Comment by astroidex** [comment]
* I only changed text in Commit https://github.com/OSGeo/OSGeoLive-doc/pull/235/commits/68aee203139ea11db84c4e624bedc92913a8c2e
* can't see why build fails

**Comment by cvvergara** [comment]
The build is still cancelled, someone with permissions on travis can restart it

**Comment by kalxas** [comment]
ok, restarting Travis now

**Pull request merged**
