### PR TITLE
update PyWPS documentation

### PR DESCRIPTION
**Pull request by tomkralidis**
Initial update of PyWPS documentation for review from PyWPS team.

**Note**: we'll squash the PR once it's reviewed and fixes are made.

### CODE REVIEW

**Comment by camerons** [comment]
Hi tomkralidis, I've reviewed the pywps Project Overview:
https://github.com/camerons/OSGeoLive-doc/tree/geopython-pywps

I've moved things around a bit.
Still missing in a screen shot.

I've only skimmed the Quickstart, but first comments:
* Needs screen shots for each step. 
* Remove the 2 lines: "PyWPS allows for the expose geospatial operations (refered as processes). PyWPS is Open Source, released under an GNU/GPL license, and runs on all major platforms (Windows, Linux, Mac OS X)."
* Remove the "Installation" section. (Note that PyWPS is already installed on OSGeo-Live

**Comment by tomkralidis** [comment]
cc @jachym 

Thanks @camerons.  I've integrated your initial comments.  We'll now work on screenshots to finish off the PR.

**Comment by jachym** [comment]
I've added some screenshots to the repository, to this branch, I hope, it's ok

**Comment by johanvdw** [comment]
Jachym, 
we should try to minify the screenshots where possible, I'll create a branch.

**Comment by tomkralidis** [comment]
@jachym are all the screenshots used/required
In the page?

**Comment by camerons** [comment]
I'll review over next 48 hours and provide feedback on number of docs required. Whatever images are created should be compressed, if not already done so. Tips on compressing images (possibly dated) is here: https://wiki.osgeo.org/wiki/Live_GIS_Add_Project#Screen_Shot and https://wiki.osgeo.org/wiki/Live_GIS_Add_Project#Logo

**Comment by camerons** [comment]
I've reviewed pywps_quickstart.rst, and inserted comments through the document, and a couple of minor changes to syntax. I've committed to:
https://github.com/camerons/OSGeoLive-doc/commits/geopython-pywps

Raw source: https://raw.githubusercontent.com/camerons/OSGeoLive-doc/geopython-pywps/en/quickstart/pywps_quickstart.rst

**Comment by camerons** [comment]
Ping @tomkralidis, @jachym ? Are you able to address review above within next few days?

**Comment by kalxas** [comment]
I am not sure we need all those screenshots. I am going to cherry-pick the commits from the first review that was addressed from @tomkralidis 
Then, please try to integrate the second round of review.

**Comment by kalxas** [comment]
@tomkralidis @jachym I have partially merged this PR.
Things to do:
1. Compress the new screenshots as @johanvdw suggested and re-commit (if needed).
2. Update based on the second review by @camerons 

We need to finalize docs by this weekend in order to cut RC1.
Thanks all.

**Comment by jachym** [comment]
Can not move with this during this week, due to family reasons. You decide, what the next step for OSGeo-Live should be - sorry for causing troubles.

**Comment by tomkralidis** [comment]
FYI I have since submitted #147

**Pull request closed without merging**
