### PR TITLE
WIP Issue 2240

### PR DESCRIPTION
**Pull request by cvvergara**
Removing unused file about contributors
&
Locale files without rst file

### CODE REVIEW

**Comment by Bakaniko** [comment]
Ok to remove if not up to date.
How can we generate contributors list ?

**Comment by kalxas** [comment]
yes it would be nice to have contributors listed somehow

**Comment by cvvergara** [comment]
Command is:
```
git shortlog --summary --numbered --email
```
What I can do later is to make a script that matches the file
- contributors.csv
- translators.csv
and will automatically add any missing name

Will mark this PR as work in progress until that script is done

**Comment by kalxas** [comment]
Just keep in mind that the original list here used to hold contributors from the SVN times that are not listed in git history

**Comment by kalxas** [comment]
@cvvergara can you please fix the conflict so we can merge?

**Comment by cvvergara** [comment]
@kalxas havent done the script so its still WIP

**Comment by kalxas** [comment]
ok thanks

**Pull request closed without merging**
