### PR TITLE
Adding pygeoapi overview and project info

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by kalxas** [comment]
The build fails because we need to merge #638 first

**Comment by Bakaniko** [comment]
Thanks @kalxas 
I believe it will be easier to merge both PR before merging into the docs.
Because there will be conflicts on projects_info.csv to resolve.
It makes more sense to make on complete PR.

Plus it is missing pygeoapi-screenshot.png, maybe we should rename home.png  in order to solve that ?

**Review by tomkralidis — APPROVED** [review]

**Comment by pvgenuchten** [comment]
looks good @kalxas

**Comment by cvvergara** [comment]
Done on #646

**Pull request closed without merging**
