### PR TITLE
Review of OSGeo-Live presentation updates

### PR DESCRIPTION
**Pull request by camerons**

### CODE REVIEW

**Comment by kalxas** [comment]
I have a conflict:
* I prefer the list of 11.0 changes from @astroidex 
* I agree with the rest of the corrections from @camerons

**Comment by activityworkshop** [comment]
For JOSM in the presentation html, I would suggest to change this sentence:

> JOSM is a desktop OpenStreetMap editor which can be used offline or for it's more advanced features than provided by the iD Editor.

Perhaps something like:

> JOSM is a desktop OpenStreetMap editor which provides many advanced features and can also be used offline.

**Comment by cvvergara** [comment]
The PR was made 2 days ago and for a reason I don't understand shows more commits than it should.

The real differences are found in this link:
https://github.com/OSGeo/OSGeoLive-doc/compare/master...camerons:presentation

**Comment by cvvergara** [comment]
Closing to create another PR without the other commits

**Pull request closed without merging**
