### PR TITLE
actinia quickstart update: new ace parser

### PR DESCRIPTION
**Pull request by neteler**
After recent (unavoidable) update of the `ace` parser, i.e. turning it into a true GRASS GIS addon, most flags and parameters have changed accordingly.  This PR updates the quickstart.

This PR affects the translations, and hence might be postponed to > v14.0.

### CODE REVIEW

**Comment by neteler** [comment]
Sorry to bother but how to get this (partially) merged? 
The old quickstart is no longer valid... would be a pity to ship v14 with a broken quickstart.

**Comment by kalxas** [comment]
I have assigned to the docs team for review

**Comment by kalxas** [comment]
@cvvergara @Bakaniko @astroidex any thoughts about this?
Would it be ok just to fix the code to avoid translation changes?

**Comment by neteler** [comment]
(I am also willing to take care of the German and Italian translations)

**Comment by neteler** [comment]
> Would it be ok just to fix the code to avoid translation changes?

Done in PR #707. This PR has been updated and the description above as well.

**Comment by cvvergara** [comment]
Sorry, missed the ping,
I see that documentation has changed on the frozen period, so for me its ok to make more changes.
But translations will be froze. aka Will not upload to transifex, and translated strings because of a change will be lost.

**Review by cvvergara — APPROVED** [review]

**Comment by cvvergara** [comment]
@neteler Thanks for the PR

**Pull request merged**
