### PR TITLE
Geomajas quickstart updated + screenshots added

### PR DESCRIPTION
**Pull request by EliotGuarini**

### CODE REVIEW

**Comment by kalxas** [comment]
Thank you @EliotGuarini for your contribution!

We will need an e-mail to the mailing list (or here) that you agree with the license.
Please send something like this:
"Hi all, I'd like to contribute XXX to OSGeo-Live. I confirm that my contributions to OSGeo-Live will be compatible with the OSGeo-Live license guidelines at the time of contribution."
as mentioned in: https://wiki.osgeo.org/wiki/Live_GIS_Disc#Git_migration
Can you please add your name in https://github.com/OSGeo/OSGeoLive-doc/blob/master/contributors.csv as part of this PR?

Thanks,
Angelos

**Comment by kalxas** [comment]
I also assume that the overview document has been reviewed and it is up to date.

**Comment by EliotGuarini** [comment]
Hi Angelos,

As requested: I'd like to contribute Geomajas to OSGeo-Live. I confirm that my contributions to OSGeo-Live will be compatible with the OSGeo-Live license guidelines at the time of contribution.
I have also added my name to the contributors document.
Regarding the overview document, this has been reviewed and is still up to date.

I hope everything is now in order. If not, please let me know.

Greetings
Eliot

**Comment by kalxas** [comment]
Thank you @EliotGuarini

**Pull request merged**
