### PR TITLE
jupyter 

### PR DESCRIPTION
**Pull request by epifanio**
Revised PR for jupyter overview and quickstarter.

### CODE REVIEW

**Comment by kalxas** [comment]
jupyter3.png should not have the placeholders listed.

**Comment by kalxas** [comment]
I think we need a quickstart update based on the latest changes: 
1. Mention the new TOC (with updated screenshot)
2. Mention the Introduction to Notebook for new users

**Comment by camerons** [comment]
I've reviewed this pull request, made a number of changes, which are now in pull request #114

**Comment by kalxas** [comment]
Superseded by #115

**Comment by kalxas** [comment]
Superseded by #116

**Pull request closed without merging**
