### PR TITLE
Update R_quickstart.rst

### PR DESCRIPTION
**Pull request by micha-silver**
Removed '>' prompt character from code examples.
Corrected a typo in last ggplot example.

### CODE REVIEW

**Comment by Bakaniko** [comment]
Hi, thanks for you interest in the R quickstart.
I do believe that the '>' sign was originally kept to simulate the R prompt.

It is one the specificities of R, like the numbered items for outputs "[1]"

I'm not for removing them.

**Comment by micha-silver** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Hi:
    
    
    On 1/11/21 10:04 PM, Nicolas Roelandt
      wrote:
    
    
      
      Hi, thanks for you interest in the R quickstart.
        I do believe that the '>' sign was originally kept to
        simulate the R prompt.
    
    That's what I understood. My suggestion was intended to simplify
      "copy-paste" for new users to try the commands, without the prompt
      interfering.
    But whatever you consider best....
    
    
    
      It is one the specificities of R, like the numbered items for
        outputs "[1]"
      I'm not for removing them.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OSGeo/OSGeoLive-doc/pull/660#issuecomment-758191298",
"url": "https://github.com/OSGeo/OSGeoLive-doc/pull/660#issuecomment-758191298",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Micha Silver
Arava Drainage Authority
cell: +972-523-665918

**Comment by cvvergara** [comment]
Based on comment I will close the PR.

**Review by Bakaniko — COMMENTED** [review]
@micha-silver I agree about the typo you detected. It returns the whole bounding box when we want the X and Y limits separately.

Can you make another PR to fix that please ?

**Pull request closed without merging**
