### PR TITLE
Jupyter reactivate overview quickstart

### PR DESCRIPTION
**Pull request by astroidex**
* checked overview and quickstart
* new screenshots were made
* reactivate the project in the project_info.csv
* changed the quickstart to the geopandas tutorial, as the mentioned GSOC tutorial was not there anymore

### CODE REVIEW

**Review by kalxas — COMMENTED** [review]
Please make sure that added screenshots are optimized with optpng

**Comment by astroidex** [comment]
> optpng

Hi kal

> Please make sure that added screenshots are optimized with optpng

Thanks for the information. Done with optipng.

**Comment by cvvergara** [comment]
You might need to do a `git pull` before doing the following changes

Add the lines for Jupiter at the end of the file follow the sintax of `pygeoapi`:
https://github.com/OSGeo/OSGeoLive-doc/blob/master/.tx/config#L783

After you do that in your computer do:
```
cd build
rm -rf *
cmake -DLOCALE=ON ..
make locale
cd ..
# personally I do, just to be on the safe side
git status
# you should see the .tx/cofig file and changes in locale/en and on locale/pot
git add .tx/config
git add locale
```
commit & push

And now push the locale files to transifex
```
tx push -s -l en
```

**Comment by astroidex** [comment]
> You might need to do a `git pull` before doing the following changes
> 
> Add the lines for Jupiter at the end of the file follow the sintax of `pygeoapi`:
> https://github.com/OSGeo/OSGeoLive-doc/blob/master/.tx/config#L783
> 
> After you do that in your computer do:
> 
> ```
> cd build
> rm -rf *
> cmake -DLOCALE=ON ..
> make locale
> cd ..
> # personally I do, just to be on the safe side
> git status
> # you should see the .tx/cofig file and changes in locale/en and on locale/pot
> git add .tx/config
> git add locale
> ```
> 
> commit & push
> 
> And now push the locale files to transifex
> 
> ```
> tx push -s -l en
> ```

Hi vicky,

I did the steps as you mentioned. Worked fine. Thank you.

**Pull request merged**
