### PR TITLE
Adding the final desktop background screenshots

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by kalxas** [comment]
@johanvdw can you please review, merge and trigger a new deb build?

**Comment by johanvdw** [comment]
build is pending.

**Comment by kalxas** [comment]
Thanks @johanvdw

**Comment by johanvdw** [comment]
Build is finished. If a build is done for an rc/release, we should probably tag them here as well.

**Comment by kalxas** [comment]
Yes, good idea, I will tag as long as we have the final iso

**Pull request merged**
