### PR TITLE
reduce rasdaman screenshot size from ~400K to 121K; review and update…

### PR DESCRIPTION
**Pull request by misev**
… the rasdaman overview and quickstart

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @misev for the update.
There are also some review comments in the following spreadsheet:
https://docs.google.com/spreadsheets/d/1Q5BaEgQtgw4O1bXyeWMlM8XtAOhUgcjZ7Y2O0FZc2H0/edit#gid=2014800150
I will add the TOC and merge.

**Comment by misev** [comment]
I have to say it's pretty hard to understand the table, is there some legend?

I'm not sure what this means, in the "11.0 comment" column of https://docs.google.com/spreadsheets/d/1Q5BaEgQtgw4O1bXyeWMlM8XtAOhUgcjZ7Y2O0FZc2H0/edit#gid=2014800150?
Update version
Improve Docs

And why are the "v11.0" and "11.0 comment" with yellow color?

**Comment by kalxas** [comment]
Hi, I added the TOC myself.
The yellows will turn green once we have tested the installation. I will post here with my test result.

**Comment by kalxas** [comment]
@misev FYI this is the build log:
```
===============================================================
Starting "install_rasdaman.sh" ...
===============================================================
--2017-06-08 12:45:32--  http://download.rasdaman.org/installer/install.sh
Resolving download.rasdaman.org (download.rasdaman.org)... 212.201.49.173
Connecting to download.rasdaman.org (download.rasdaman.org)|212.201.49.173|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9226 (9.0K) [text/x-sh]
Saving to: 'install.sh'

     0K .........                                             100% 33.4M=0s

2017-06-08 12:45:32 (33.4 MB/s) - 'install.sh' saved [9226/9226]

[0mChecking if installer needs to update...[0m
[0mInstaller is at latest version.[0m

[0mStrategy building is handled by the General Strategy Builder.[0m
[1mReview the installation settings:[0m
[0m
Installation path: /opt/rasdaman/
Version: master
Update: False
User: user
Debug: False
Communication protocol: rasnet
Database type: sqlite
  Database data directory: /opt/rasdaman/data/
Rasdaman binary: http://download.rasdaman.org/packages/binary/rasdaman.tar.gz
Petascope enabled: True
  Petascope database url: jdbc:postgresql://localhost:5432/petascopedb
  Petascope database user: user
  Petascope server type: tomcat
  Tomcat home: /var/lib/tomcat8
Secore enabled: True
Run systemtest: False
Rasdaman demo data: False
Petascope demo data: False
[0m
[1mValidating system...[0m
[0mCleaning up any old rasdaman files...[0m
[0mOld rasdaman files cleaned up successfully.[0m
[1mSystem was validated.[0m
[1mInstalling third party dependencies on Ubuntu 16.04...[0m
[0mInstalling packages ['make', 'libtool', 'gawk', 'autoconf', 'bison', 'flex', 'git', 'g++', 'unzip', 'libboost-all-dev', 'libtiff-dev', 'libgdal-dev', 'zlib1g-dev', 'libffi-dev', 'libedit-dev', 'libreadline-dev', 'libecpg-dev', 'libsqlite3-dev', 'libgrib-api-dev', 'libgrib2c-dev', 'curl', 'libnetcdf-cxx-legacy-dev', 'openjdk-8-jdk', 'maven', 'ant', 'libgdal-java', 'postgresql', 'postgresql-contrib', 'sqlite3', 'zlib1g', 'gdal-bin', 'python-dev', 'debianutils', 'python-dateutil', 'python-lxml', 'python-grib', 'python-pip', 'python-gdal', 'libnetcdf-dev', 'netcdf-bin', 'libecpg6', 'libboost-all-dev', 'libedit-dev', 'libreadline-dev', 'libnetcdf-c++4', 'python-netcdf4', 'tomcat8']... [0m
[0mPackages installed successfully.[0m
[0mChecking user user....[0m
[0mUser user checked successfully.[0m
[0mInstalling pip packages ['glob2']... [0m
[0mPip packages installed successfully.[0m
[0mCreating directory structure...[0m
[0mDirectory structure created successfully.[0m
[0mSetting up the PATH environment variable in '/etc/profile.d/rasdaman.sh'...[0m
[0mThe PATH environment variable was set up successfully.[0m
[1mThird party dependencies installed successfully.[0m
[1mRetrieving rasdaman...[0m
[1mRasdaman retrieved successfully[0m
[1mBuilding rasdaman...[0m
[0mDownloading and installing rasdaman binaries...[0m
[0mDownloaded and installed rasdaman binaries successfully[0m
[0mDownloading and deploying petascope war...[0m
[0mDeploying rasdaman.war...[0m
[0mrasdaman.war deployed successfully.[0m
[0mDownloaded and installed petascope war...[0m
[0mDownloading and deploying secore war...[0m
[0mDeploying def.war...[0m
[0mdef.war deployed successfully.[0m
[0mDownloaded and installed secore war...[0m
[1mRasdaman was built successfully.[0m
[1mPreparing rasdaman...[0m
[0mPreparing rasmgr.conf...[0m
[0mrasmgr.conf prepared successfully.[0m
[0mPreparing Rasdaman SQLite database...[0m
[0mRasdaman SQLite database was prepared.[0m
[0mPreparing petascope database using OSGeo preparer...[0m
[0mPetascope database was prepared.[0m
[1mRasdaman prepared successfully.[0m
[1mFinalizing installation...[0m
[0mCustomizing rasdaman for OSGeo Live...[0m
[0mCreating starting scripts...[0m
[0mStarting scripts successfully created.[0m
[0mCreating desktop icons...[0m
[0mDesktop icons created successfully.[0m
[0mStriping binaries and removing unneeded files for OSGeo Live...[0m
[0mBinaries stripped successfully.[0m
[0mDeploying local earthlook...[0m
[31mAn error has occured while executing this command: wget http://kahlua.eecs.jacobs-university.de/~earthlook/osgeo/earthlook.tar.gz -O earthlook.tar.gz.Check the log at /tmp/rasdaman.install.log for more details.
Preview of the error:
 Return code: 8
 Stderr: --2017-06-08 12:51:44--  http://kahlua.eecs.jacobs-university.de/~earthlook/osgeo/earthlook.tar.gz
Resolving kahlua.eecs.jacobs-university.de (kahlua.eecs.jacobs-university.de)... 212.201.49.173
Connecting to kahlua.eecs.jacobs-university.de (kahlua.eecs.jacobs-university.de)|212.201.49.173|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-08 12:51:44 ERROR 404: Not F
 Stdout:[0m
ERROR: The installer returned an error code. The installation might not be valid.
rasdaman: unrecognized service
 * Stopping Tomcat servlet engine tomcat8
   ...done.
sed: can't read /var/www/html/rasdaman-demo/demo/demo-frames/2d/app.js: No such file or directory
sed: can't read /var/www/html/rasdaman-demo/demo/demo-frames/ww3d/app.js: No such file or directory
```

**Comment by misev** [comment]
I fixed the URL, would you retry?

**Comment by kalxas** [comment]
thanks, will retry.

**Comment by cvvergara** [comment]
@misev 

I am checking the documentation generation.
There is this problem:
```
rasdaman_overview.rst:: WARNING: image file not readable: images/screenshots/1024x768/rasdaman-collage.png
```
https://travis-ci.org/cvvergara/OSGeoLive-doc/builds/244959785#L634

The image that is uploaded is a jpg

```
$ ls images/screenshots/1024x768/rasd*
images/screenshots/1024x768/rasdaman-collage.jpg
```

So, my question is, about your intention.
(if option 1, I do it)

### option 1
This image the correct image
https://github.com/OSGeo/OSGeoLive-doc/blob/master/images/screenshots/1024x768/rasdaman-collage.jpg
and in `en/overview/rasdaman_overview.rst` this:
```
.. image:: ../../images/screenshots/1024x768/rasdaman-collage.png
```
Needs to be changed to:
```
.. image:: ../../images/screenshots/1024x768/rasdaman-collage.jpg
```

### option 2

This is correct:
```
.. image:: ../../images/screenshots/1024x768/rasdaman-collage.png
```
And `rasdaman-collage.png` needs to be uploaded

**Comment by misev** [comment]
Option 1, sorry I've missed to update the doc properly.

**Comment by cvvergara** [comment]
fixed in:

https://github.com/OSGeo/OSGeoLive-doc/pull/213/commits/39bcbacb157f1b9cd9fbdd82db6e1a7c9762f827

**Pull request merged**
