### PR TITLE
Fixes by Luca

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by kalxas** [comment]
@johanvdw Luca (@lucadelu) has fixed the make html for presentations. This works ok for me locally.
I just wanted a confirmation that it works for the debian package as well before I merge.
I also need to update the adhoc build script right after we merge.

**Comment by kalxas** [comment]
Lets test this in Launchpad by merging.

**Comment by kalxas** [comment]
Actually, the new deb created cannot be updated cleanly through dpkg.
I tested in the released iso (amd64) by adding the daily ppa and the docs cannot update.
Still looking at this...

**Comment by johanvdw** [comment]
In only noticed this mail now.  It surprises me that this can not be
updates (looking at the diff).

**Pull request merged**
