### PR TITLE
52nSOS: documentation update for OSGeoLive 12.0

### PR DESCRIPTION
**Pull request by EHJ-52n**

### CODE REVIEW

**Comment by cvvergara** [comment]
@EHJ-52n 
Because this PR changes the projects version info, I cant merge the changes of the documentation until @kalxas verifies that is the one that is installed on the disk

**Comment by EHJ-52n** [comment]
So, we are waiting for https://github.com/OSGeo/OSGeoLive/pull/209 to be merged before this one can be merged?

@cvvergara @kalxas

**Comment by EHJ-52n** [comment]
Hi @kalxas, @cvvergara ,
I will go on vacation on Friday and want to finish the German translation asap before Friday. Therefore I need this to be merged.

What is holding you back in merging this PR?

I will provided anything required asap.
Kind regards,
Eike

**Comment by cvvergara** [comment]
Thanks for the fixes

**Pull request merged**
