### PR TITLE
Presentation script

### PR DESCRIPTION
**Pull request by lucadelu**
Fixed some problems in the presentation script and in the Makefile

### CODE REVIEW

**Comment by kalxas** [comment]
@lucadelu we need to make sure that these changes do not conflict with the current package.
@johanvdw can you please try a build with the above change to make sure we won't break the ppa?

**Comment by lucadelu** [comment]
@kalxas are you able to compile presentation without these changes?

**Comment by kalxas** [comment]
There is an automated build for each commit in this repository:
https://launchpad.net/~johanvdw/+archive/ubuntu/osgeolive-doc-daily

And it compiles without problems.
Last time I checked it worked for me too.

I am not against this fix, as long as we make sure the ppa will still work

**Comment by johanvdw** [comment]
I'll try making a build later today.

**Comment by johanvdw** [comment]
I tested this locally and the build/installation work fine.

**Pull request merged**
