### PR TITLE
Remove presentation.rst files, correct typo

### PR DESCRIPTION
**Pull request by activityworkshop**

### CODE REVIEW

**Comment by cvvergara** [comment]
With the removal of the files, now these warnings appear

https://travis-ci.org/OSGeo/OSGeoLive-doc/builds/246514939#L3332

So, I will try to figure out what changes need to be done on the documentation such that there are no longer references the deleted files.

**Comment by cvvergara** [comment]
also presentation.rst is referenced in the Makefile
https://travis-ci.org/OSGeo/OSGeoLive-doc/builds/246514939#L856

**Comment by cvvergara** [comment]
@kalxas 
Can you do the fixing on the Makefile, It has scripts that reference the:
presentation.rst
presentation.html

https://github.com/OSGeo/OSGeoLive-doc/blob/master/Makefile#L66
https://github.com/OSGeo/OSGeoLive-doc/blob/master/Makefile#L94
https://github.com/OSGeo/OSGeoLive-doc/blob/master/Makefile#L220

(I use vi, and have my tabs setup to spaces, and its not suitable to edit a Makefile)

**Comment by cvvergara** [comment]
@kalxas 
never mind, I think I could fix it using another editor

**Comment by kalxas** [comment]
Thanks @cvvergara

**Pull request merged**
