### PR TITLE
Add travis/on master

### PR DESCRIPTION
**Pull request by cvvergara**
## tasks

- [x] add .travis.yml to master branch
- [x] fix errors TBD
  - [x] fix on English files
- [x] resolve for missing images in:
  - [x] rasdaman
  - [x] sponsor
- [x] Add verbosity to travis to catch other warnings
- [x] before merging update fork/branch to catch latest changes on master
- Postponing missing images
  - Saga
  - ncWMS

Travis executions of this PR can be seen in:
https://travis-ci.org/cvvergara/OSGeoLive-doc/builds/245801524

### CODE REVIEW

**Comment by cvvergara** [comment]
@kalxas 

I made some comments on the PR about missing images:

project | comment
--------- | ---------------
SAGA | https://github.com/OSGeo/OSGeoLive-doc/pull/204#issuecomment-309778929 
rasdaman | https://github.com/OSGeo/OSGeoLive-doc/pull/206#issuecomment-309791604
ncWMS |  https://github.com/OSGeo/OSGeoLive-doc/pull/203#issuecomment-309783733

**Comment by cvvergara** [comment]
@camerons 

I could not find the PR where you "deleted" the austrailan goverment from being a sponsor, So I post in here:

Now Sphinx complains about  missing image `OSDM_stacked.png`
```
https://github.com/OSGeo/OSGeoLive-doc/tree/master/images/logos
image file not readable: en/../images/logos/OSDM_stacked.png
```
https://travis-ci.org/cvvergara/OSGeoLive-doc/builds/245057963#L635

On this file:
https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/sponsors.rst

Maybe you forgot to remove the "sphinx code" that makes use of that image that is being used in all this files:
https://github.com/OSGeo/OSGeoLive-doc/search?utf8=%E2%9C%93&q=osdm&type=

I must tell you that the English file fails, but once the English passes, the other languages with fail because the image is not there, unless you delete the lines:

```
.. image:: ../images/logos/OSDM_stacked.png
  :alt: The Australian Government's Office of Spatial Data Management
  :target: http://www.osdm.gov.au
```
code on the all the already translated sponsors.rst files.

**Comment by kalxas** [comment]
Thanks @cvvergara 
This looks good.
Should we merge now?

**Comment by cvvergara** [comment]
@kalxas 

Waint until build finishes:
https://travis-ci.org/cvvergara/OSGeoLive-doc/builds/245801524

**Pull request merged**
