### PR TITLE
Add Quickstart on setting up OSGeoLive on Hyper-V

### PR DESCRIPTION
**Pull request by geographika**
Draft page for Hyper-V setup. 
This approach would rely on a converted vmdk to vhdx disk image. 
See discussions at http://osgeo-org.1560.x6.nabble.com/Hyper-V-VMs-tt5363993.html

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @geographika for your contribution!
Can you please send an e-mail to the mailing list accepting the license?
https://trac.osgeo.org/osgeolive/wiki/Source_code#Commitaccess

**Comment by johanvdw** [comment]
And consider adding your name to the contributors.txt.

**Comment by johanvdw** [comment]
We may be able to make these images a little smaller, just a second.

**Comment by johanvdw** [comment]
Consider making a new pull request with the same text, but the attached images, or commit to this branch (and when we merge choose "squash"). That way we will have smaller images in the archive and git history.
[tinified.zip](https://github.com/OSGeo/OSGeoLive-doc/files/2008999/tinified.zip)

Note I use https://tinypng.com/ for this.

**Comment by geographika** [comment]
@johanvdw - thanks for the suggestion - minified images attached

**Comment by astroidex** [comment]
* Mail about License Confirmation from Seith arrived  Wednesday 16.5.2018 13:48 on MailingList https://lists.osgeo.org/pipermail/osgeolive/2018-May/013099.html

**Comment by cvvergara** [comment]
Commits of  #371 & #374 squashed into one on PR #382

**Pull request closed without merging**
