### PR TITLE
jupyter quickstart

### PR DESCRIPTION
**Pull request by epifanio**

### CODE REVIEW

**Comment by camerons** [comment]
I've reviewed, put comments into the source: https://raw.githubusercontent.com/camerons/OSGeoLive-doc/master/en/quickstart/jupyter_quickstart.rst
Also have made some minor changes.

**Comment by kalxas** [comment]
Please try to commit as less changes to binary files as possible (images) and make sure to "optipng -o 9" before committing them to the docs.

**Comment by epifanio** [comment]
Can't access anymore to: 

> I've reviewed, put comments into the source: https://raw.githubusercontent.com/camerons/OSGeoLive-doc/master/en/quickstart/jupyter_quickstart.rst
Also have made some minor changes.

**Comment by epifanio** [comment]
I did few changes. 

I added a link to the html documentation (web version) i can replace it with the pdf
I can’t “touch” the osgeolive repo .. I screwed up my fork last day, can you please add the ``wget`` line in the install jupyter script to get the pdf? 
Then let me know the location to update the link on the rst file.

**Comment by epifanio** [comment]
I had some conflict with git, I opened a new PR:  https://github.com/OSGeo/OSGeoLive-doc/pull/112  . it uses same files (just wirth fixed conflicts) I'll close this.

**Pull request closed without merging**
