### PR TITLE
Improving the documentation

### PR DESCRIPTION
**Pull request by cvvergara**
Fixes:
* https://github.com/cvvergara/OSGeoLive-doc/issues/35
* https://github.com/cvvergara/OSGeoLive-doc/issues/37
* https://github.com/cvvergara/OSGeoLive-doc/issues/38
* https://github.com/cvvergara/OSGeoLive-doc/issues/39
* https://github.com/cvvergara/OSGeoLive-doc/issues/41
* https://github.com/cvvergara/OSGeoLive-doc/issues/43
* https://github.com/cvvergara/OSGeoLive-doc/issues/44
* https://github.com/cvvergara/OSGeoLive-doc/issues/45
* https://github.com/cvvergara/OSGeoLive-doc/issues/64
* https://github.com/cvvergara/OSGeoLive-doc/issues/65
* [trac 2040](https://trac.osgeo.org/osgeolive/ticket/2040)

### CODE REVIEW

**Comment by cvvergara** [comment]
I know my PR are difficult to "review" ;)
But its a way to say "Hey guys, have a look"

**Comment by cvvergara** [comment]
@Bakaniko 
maybe you can check also

**Comment by kalxas** [comment]
Do we need a second review before we merge?

**Comment by cvvergara** [comment]
@kalxas 
I will be reviewing with @Bakaniko now

**Pull request merged**
